### ISSUE TITLE
Pyramidio fails when the output path has a space in it

### ISSUE THREAD

**Issue by PolarBean** [darwinjob/pyramidio-bioformats#11]
related to this stackoverflow issue, you may need to encode the path
https://stackoverflow.com/questions/4992317/illegal-character-in-path-at-index-16

**Comment by darwinjob** [comment]
Based on my (who cares) experience having spaces, dots or language specific symbols (øæå) is a bad idea in general and should be avoided. But this is fixable of course.

**Comment by PolarBean** [comment]
of course, the only reason I ask is that users put spaces in the file names. We have a number of options of course (preventing this behaviour, or automatically substituting it for underscores). though if pyramidio could handle this it would be nice

**Comment by darwinjob** [comment]
> substituting it for underscores

FYI there is a script for that too.

**Comment by PolarBean** [comment]
sure but then I have to keep track of duplicates (ie, dataset 1 and dataset_1) now have identical names

**Comment by darwinjob** [comment]
The folder/file name "dataset 1" shouldn't exist. Nesys is not the place where an experience is appreciated but believe me, I've been thru this before in N3, the only proper way to resolve this is to make the users follow the naming convention. Otherwise you will stuck in an endless loop fixing all kind of user naming fantasies. 
I'll still try to fix this.

**Comment by darwinjob** [comment]
Fixed for spaces. Will be available in the new release.
Probably relates to https://github.com/darwinjob/pyramidio-bioformats/issues/5 too.

**Comment by PolarBean** [comment]
fantastic!!
