### ISSUE TITLE
Pyramidio doesnt always create all the layers

### ISSUE THREAD

**Issue by PolarBean** [darwinjob/pyramidio-bioformats#12]
See the below example, it doesnt load at the highest level only when zoomed in:
https://miosdv.apps-dev.hbp.eu/index.html?bucket=https://tar-svc-test.apps.hbp.eu/fakebucket/?url=https://data-proxy.ebrains.eu/api/v1/buckets/ewb-fc6b509d-8398-437e-a86e-627a41f3ed15?prefix=.nesysWorkflowFiles/zippedPyramids/test_T2star

Please see the below link for the original images:
https://data-proxy.ebrains.eu/ewb-fc6b509d-8398-437e-a86e-627a41f3ed15?prefix=.nesysWorkflowFiles%2ForiginalImages%2Ftest_T2star%2F

**Comment by darwinjob** [comment]
Tested all 3 PNGs. Can't confirm that any layers (pyramid levels) are skipped. All the levels are created as they should:
<img width="486" alt="image" src="https://github.com/darwinjob/pyramidio-bioformats/assets/358762/839f563b-df34-4ebb-b3dc-58bbba31d2e3">

BTW there's a message in the log:
`gov.nist.isg.pyramidio.cli.Main getCalculatedPercentage
WARNING: Channel count > 3. Is alpha channel present? The output pyramid might be corrupted. See https://github.com/darwinjob/pyramidio-bioformats/issues/1`

So this is the expected behavior. The content of the folders is a different topic. Closing the issue.

**Comment by PolarBean** [comment]
but the images inside the folders are not created properly so this is not functional

**Comment by darwinjob** [comment]
The name of your issue is misleading: "Pyramidio doesnt always create all the layers"
It does create all the layers. I repeat: the content of the folders is a different topic. Namely the one about the alpha channel in an input image https://github.com/darwinjob/pyramidio-bioformats/issues/13
It will be fixed there. No need to create duplicates.

**Comment by PolarBean** [comment]
ah ok thats good to hear :)
